version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
    - bodyclose
    - nilerr
    - nilnil
    - errorlint
  exclusions:
    generated: lax

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/sayze/homelab-utils
